# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fafc65df8aa91ca91e66cbf53455b3a4"
name = "dialnexa"
application_url = "https://dialedin-pi.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://dialedin-pi.vercel.app/api/auth",
  "https://dialedin-pi.vercel.app/auth/callback",
  "https://dialedin-pi.vercel.app/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
